# Generated by Django 2.0.6 on 2018-06-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
